# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20181128_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='contributor',
            new_name='contributors',
        ),
    ]
